# Generated by Django 3.2.7 on 2021-10-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211021_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
